import { MahgerViewModel } from './Mahger';

export class DataViewModel {
  id: number;
  MedicalCenterId: number;
  startDateTime: Date;
  by: string;
  medicalCentername: string;
  ind1: number;
  ind2: number;
  ind3: number;
  ind4: number;
  ind5: number;
  ind6: number;
  ind7: number;
  ind8: number;
  ind9: number;
  ind10: number;
  ind11: number;
  ind12: number;
  ind13: number;
  ind14: number;
  ind15: number;
  ind16: number;
  ind17: number;
  ind18: number;
  ind19: number;
  ind20: number;
  ind21: number;
  ind22: number;
  ind23: number;
  ind24: number;
  ind25: number;
  ind26: number;
  ind27: number;
  ind28: number;
  ind29: number;
  ind30: number;
  ind31: number;
  iscomplate: boolean;
  persent: number;
  mahjarsdataList: MahgerViewModel[];
  steps: string;
}
